<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251201025248 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, workflow_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_741D53CD2C7C2CBA ON place (workflow_id)');
        $this->addSql('CREATE TABLE transition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, from_place_id INT NOT NULL, to_place_id INT NOT NULL, workflow_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F715A75A4B494283 ON transition (from_place_id)');
        $this->addSql('CREATE INDEX IDX_F715A75AC0FF3CB7 ON transition (to_place_id)');
        $this->addSql('CREATE INDEX IDX_F715A75A2C7C2CBA ON transition (workflow_id)');
        $this->addSql('CREATE TABLE workflow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, initial_place VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE place ADD CONSTRAINT FK_741D53CD2C7C2CBA FOREIGN KEY (workflow_id) REFERENCES workflow (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transition ADD CONSTRAINT FK_F715A75A4B494283 FOREIGN KEY (from_place_id) REFERENCES place (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transition ADD CONSTRAINT FK_F715A75AC0FF3CB7 FOREIGN KEY (to_place_id) REFERENCES place (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transition ADD CONSTRAINT FK_F715A75A2C7C2CBA FOREIGN KEY (workflow_id) REFERENCES workflow (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE place DROP CONSTRAINT FK_741D53CD2C7C2CBA');
        $this->addSql('ALTER TABLE transition DROP CONSTRAINT FK_F715A75A4B494283');
        $this->addSql('ALTER TABLE transition DROP CONSTRAINT FK_F715A75AC0FF3CB7');
        $this->addSql('ALTER TABLE transition DROP CONSTRAINT FK_F715A75A2C7C2CBA');
        $this->addSql('DROP TABLE place');
        $this->addSql('DROP TABLE transition');
        $this->addSql('DROP TABLE workflow');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
