<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251201162126 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE transition_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transition_name VARCHAR(255) NOT NULL, from_place VARCHAR(255) NOT NULL, to_place VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subject_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AEBF54B723EDC87 ON transition_log (subject_id)');
        $this->addSql('ALTER TABLE transition_log ADD CONSTRAINT FK_AEBF54B723EDC87 FOREIGN KEY (subject_id) REFERENCES workflow_subject (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE transition_log DROP CONSTRAINT FK_AEBF54B723EDC87');
        $this->addSql('DROP TABLE transition_log');
    }
}
